version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
        - db
  db:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"


volumes:
    mongo-db:
